import { ObjectId } from "bson";

export class AIToolInfo {
  _id: string; // MongoDB ObjectId as string
  functionName: string;
  functionDescription: string;
  agentId : string;
  agentName : string;
  category : string;
  historyMode : string;
  functionSchemaIsStrict: string;
  functionParameters: string | null; // JSON schema for function parameters, if any
  callGPT: boolean; // Indicates if the tool should call GPT for further processing
  message: string; // Message associated with the tool
  isActive: boolean; // Indicates if the tool should be called
  taskCompleted: boolean; // Indicates if the tool should be called

  IsMcp:boolean
  TransportType:string
  Path:string
}
export class Agents{
  _id:string = new ObjectId().toHexString()
  name:string
  model:string
  provider:string
  apiKey:string
  prompt:string
  agent_id:string
  chatbotId:string
  mainAgent:boolean = false
  intentResponse:IntentResponse[] = []
  aiIntents:boolean = false
  startWithoutHistory:boolean = false
  maxMemoryLength:number
  routing:Routing[] = []
  promptSections:promptSections = new promptSections()
  tools:AgentTool[] = []
  subAgents:SubAgent[] = []
  state:StateVariable[] = []
  globalInstruction:string
  description:string
  parentAgentId:string
  agentHandoffMode:number
}

export class IntentResponse{
    intent:string
    response:string
}
export class Routing{
  intent:string
  taskId:string
  variables:VariableValue[] = []
}
export class VariableValue{
  variableId:string
  variableName:string
  value:string
}
export class promptSections {
  conversationFlow:string
  crtitcalNote:string
  fewShotExamples:string
  functionCallRules:string
  identity:string
  responseStyle:string
}

export class SubAgent{
  agentId:string
  name:string
  description:string
}
export class StateVariable{
  variableId:string
  name:string
  defaultValue:string
}

export class SubAgentSelected{
  agentId:string
  name:string
  description:string
  selected:boolean
  subAgentParentId:string
}

export class AgentTool{
  toolId:string
  name:string
  description:string
}
export class AIModels {
  _id: string; // Optional because it may be generated by MongoDB
  provider!: string;
  apiKey!: string;
  models: Models[] = [];
}
export class Models {
  model!: string;
  promptRate!: number;
  completionRate!: number;
  cacheRate!: number;
}

export interface AIIntentModel {
  _id?: string;
  intent: string;
  response: string;
  ChatbotId: string;

  mode?: string;       // 'intent' or 'topic'
  examples?: string[];
}
